### ISSUE TITLE
Check PGP signature while building package

### ISSUE THREAD

**Issue by c-mauderer** [paulfurley/smart-label-printer-slp-linux-driver#5]
Hello @paulfurley,

I updated my Arch package to use your repository. But I'm still thinking about how to check the signature like discussed [here](https://github.com/paulfurley/smart-label-printer-slp-linux-driver/pull/2#issuecomment-275456821). Eventually you have an Idea how I could manage that.

I'm not sure whether you are familiar with the way Arch packages are built. If yes you can just skip the next paragraphs and just read the last one.

Basically the file that describe the build (called "PKGBUILD") is a shell script with some functions and variables with special names. These will be called by a very big shell script called "makepkg" that is distributed together with the package manager.

AUR is the "Arch User Repository". It is a place where everyone can upload PKGBUILD files. If I want to use a package from AUR, I can download the PKGBUILD (and eventually some necessary additional files) from AUR and build the package on my system. So there are no binary packages but only the information how to build them.

In most cases the sources are downloaded directly from the projects file server or source repository. Normal files can easily be verified using a checksum. But currently there is no build in way to check the PGP signatures of a git commit.

No my problem is, that I can't just get your key on my local machine and check the signature with it but I would have to distribute it together with the PKGBUILD. Do you have an idea how to verify a commit against a special key? `git verify-commit` seems only to verify against the local key ring and distributing an gnupg configuration directory and changing the `GNUPGHOME` environment variable to point to it feels like an ugly hack.

**Comment by fawkesley** [comment]
Hey @c-mauderer 

I know the `GNUPGHOME` thing is a bit of a hack, but I think it's the right thing to do (it's certainly not the first script I've seen to do it!)

```
export GNUPGHOME=$(mktemp -d)
gpg --keyserver pool.sks-keyservers.net --recv-key A999B7498D1A8DC473E53C92309F635DAD1B5517
git verify-commit master
```

**Comment by c-mauderer** [comment]
Hello @paulfurley,
I'll try to take a look at that at the weekend. Since last time I have changed this packet, I have seen a `validpgpkeys` entry (or similar) in some of the PKGBUILD files. I'm not sure whether they are applicable for git sources or how to use them but I'll try whether they can be used.

**Comment by fawkesley** [comment]
Cool yeah, good idea, let me know if you find a good solution, sounds like a good blog post!                                                                                                                                                                        Sent on the move                                                                                                                                                                           From: notifications@github.comSent: 20 June 2018 7:46 pmTo: smart-label-printer-slp-linux-driver@noreply.github.comReply to: reply@reply.github.comCc: paul@paulfurley.com; mention@noreply.github.comSubject: Re: [paulfurley/smart-label-printer-slp-linux-driver] Check PGP signature while building package (#5)  Hello @paulfurley,
I'll try to take a look at that at the weekend. Since last time I have changed this packet, I have seen a validpgpkeys entry (or similar) in some of the PKGBUILD files. I'm not sure whether they are applicable for git sources or how to use them but I'll try whether they can be used.

**Comment by c-mauderer** [comment]
If you (maybe) want to write a blog post, I'll try to provide some more information. Note that this will lead to some more status updates than might would be necessary.

Current status:

I found out that the official documentation regarding that topic is quite sparse. To be exact: I found two mentions of PGP checks in the Arch Wiki: https://wiki.archlinux.org/index.php/PKGBUILD#validpgpkeys and https://wiki.archlinux.org/index.php/Makepkg#Signature_checking. Basically these two sections tell me that if there is a `.asc` or `.sig` in the sources, a check with the users key ring will be done. If validpgpkeys is present, only a key with these signature will be accepted. If the key is not in the key ring an error message will be shown.

Some of the active AUR helper can automatically fetch a key. See https://wiki.archlinux.org/index.php/AUR_helpers#Active. All other users will have to read the error message and import the PGP key for themselves. It's an unstable AUR package. The user should know what he tries to do. So I would say it is OK if the user has to read an error message and react accordingly.

`makepkg` - the tool to build a package - has an `--skippgpcheck` option. That's even a simple way around the PGP check. Whatever solution I find should try to respect that option.

Also I haven't followed the whole call tree, there is a file called `/usr/share/makepkg/integrity/verify_signature.sh` in the package build system that seems to be responsible for checking PGP signatures. This file contains the following lines:
```
		if [[ $proto = git* ]]; then
			verify_git_signature "$netfile" "$statusfile" || continue
		else
			verify_file_signature "$netfile" "$statusfile" || continue
		fi
```
So it seems quite clear that verifying git signatures should already be implemented. I'll try to find out how to use it.

**Comment by c-mauderer** [comment]
Regarding which sources are checked:

`makepkg` calls a `check_source_integrity` function (implemented in `/usr/share/makepkg/integrity.sh`. That one checks whether the PGP check should be done (see [1]) and then calls the `check_pgpsigs` which contains the code snipped posted in the last comment.

[1]: The decision whether a check should be done or not depends on two parts:
1. The command line parameters (like `--skippgpcheck`).
2. A function with the name `source_has_signatures`. This function again has two checks:
  - Whether there is some source file which matches the following expression: `*.@(sig?(n)|asc)`
  - Whether there is a query `signed` at the URL. That one is a little hard to find: https://git.archlinux.org/pacman.git/commit/?id=eaa82b4d0775252856a4e54a6f2a9ea191cf0b8f (Interesting detail: This has been implemented 26 days before I opened this ticket. So if I had searched enough back then, I might would have even found it.)

To make a long story short: It looks like it might could be enough to add a `validpgpkeys` field to my PKGBUILD and append a `?signed` to the URL. I'll experiment with that and report back as soon as I can say more.

**Comment by c-mauderer** [comment]
And a test showed: It really was that simple. See https://aur.archlinux.org/cgit/aur.git/commit/?h=sii-slp-cups-git&id=c5433ee0c249a3ee40b749f82e9d05be5c5116c2

With that I now have the following behaviour:
- If my keyring doesn't contain your key, makepkg stops with the following message:
```
==> Verifying source file signatures with gpg...
    sii-slp-cups git repo ... FAILED (unknown public key 0AC6AD63E8E8A9B0)
==> ERROR: One or more PGP signatures could not be verified!
```
- If I have the key, the signature check passes.
- One of the AUR helpers I use (`aurman`) tells me if I don't have the key in my key ring and offers to import it:
```
?? PGP Key A999B7498D1A8DC473E53C92309F635DAD1B5517 found in PKGBUILD of sii-slp-cups-git and is not known yet. Do you want to import the key? Y/n: 
```

I would say that this is a good behavior for an AUR package. Therefore I'll close this ticket.

**Comment by c-mauderer** [comment]
I forgot to say: I don't have an blog. But if you want to use any of my comments for a blog post, feel free to use it.
